name: redd-block
options:
  bundleIdPrefix: com.reddblock
  deploymentTarget:
    iOS: 16.0
fileGroups: [../../src]
configs:
  debug: debug
  release: release
settingGroups:
  app:
    base:
      PRODUCT_NAME: "Digital Habits Blocker"
      PRODUCT_BUNDLE_IDENTIFIER: com.reddblock
targetTemplates:
  app:
    type: application
    sources:
      - path: Sources
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      groups: [app]
targets:
  redd-block_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Externals
        excludes:
          - "**/*.a"
      - path: redd-block_iOS
      - path: Shared
      - path: assets
        buildPhase: resources
        type: folder
      - path: LaunchScreen.storyboard
    info:
      path: redd-block_iOS/Info.plist
      properties:
        CFBundleDisplayName: "Digital Habits: Blocker"
        LSRequiresIPhoneOS: true
        ITSAppUsesNonExemptEncryption: false
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [arm64, metal]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: 3.8.10
        CFBundleVersion: "3.8.10"
    entitlements:
      path: redd-block_iOS/redd-block_iOS.entitlements
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      base:
        ENABLE_BITCODE: false
        ARCHS: [arm64]
        VALID_ARCHS: arm64
        MARKETING_VERSION: "3.8.10"
        CURRENT_PROJECT_VERSION: "3.8.10"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: JD647S9RT6
        LIBRARY_SEARCH_PATHS[arch=x86_64]: $(inherited) $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        LIBRARY_SEARCH_PATHS[arch=arm64]: $(inherited) $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
        OTHER_LDFLAGS: $(inherited) -lapp
      groups: [app]
    dependencies:
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - sdk: WebKit.framework
      - target: ReddBlockMonitor
      - target: ReddBlockShield
    preBuildScripts:
      - script: export PATH="$HOME/.cargo/bin:$PATH" && cd "${SRCROOT}/../../.." && npx tauri ios xcode-script -v --platform ${PLATFORM_DISPLAY_NAME:?} --sdk-root ${SDKROOT:?} --framework-search-paths "${FRAMEWORK_SEARCH_PATHS:?}" --header-search-paths "${HEADER_SEARCH_PATHS:?}" --gcc-preprocessor-definitions "${GCC_PREPROCESSOR_DEFINITIONS:-}" --configuration ${CONFIGURATION:?} ${FORCE_COLOR} ${ARCHS:?}
        name: Build Rust Code
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Externals/x86_64/${CONFIGURATION}/libapp.a
          - $(SRCROOT)/Externals/arm64/${CONFIGURATION}/libapp.a
  ReddBlockMonitor:
    type: app-extension
    platform: iOS
    sources:
      - path: ReddBlockMonitor
      - path: Shared
    info:
      path: ReddBlockMonitor/Info.plist
      properties:
        CFBundleDisplayName: ReddBlockMonitor
        NSExtension:
          NSExtensionPointIdentifier: com.apple.deviceactivity.monitor-extension
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ReddBlockMonitor
    entitlements:
      path: ReddBlockMonitor/ReddBlockMonitor.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.reddblock.monitor
        PRODUCT_NAME: ReddBlockMonitor
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: JD647S9RT6
    dependencies:
      - sdk: DeviceActivity.framework
      - sdk: ManagedSettings.framework
      - sdk: FamilyControls.framework
  ReddBlockShield:
    type: app-extension
    platform: iOS
    sources:
      - path: ReddBlockShield
      - path: Shared
    info:
      path: ReddBlockShield/Info.plist
      properties:
        CFBundleDisplayName: ReddBlockShield
        NSExtension:
          NSExtensionPointIdentifier: com.apple.ManagedSettingsUI.shield-configuration-service
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShieldConfigurationExtension
    entitlements:
      path: ReddBlockShield/ReddBlockShield.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.reddblock.shieldconfiguration
        PRODUCT_NAME: ReddBlockShield
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: JD647S9RT6
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: "YES"
    dependencies:
      - sdk: ManagedSettings.framework
      - sdk: ManagedSettingsUI.framework